### ISSUE TITLE
Use case: (Test of Gravizo) simulate a water distribution system's hydraulics

### ISSUE THREAD

**Issue by dbhart** [OpenWaterAnalytics/next-net#11]
So, mostly this issue is so that we can all practice with making graphics using Gravizo. I am going to try to create a simple UML-style Use Case diagram for a basic user who wants to run their network model and look at results in a text file.

![Alt text](https://g.gravizo.com/svg?
@startuml;
User -> Start;
User --> Run the simulation : A small label;
User --> View the results ;
@enduml)

Hmmm... It does not look like this works in issues to put these in?

**Comment by dbhart** [comment]
![Alt text](https://g.gravizo.com/source/custom_mark10?https://raw.githubusercontent.com/TLmaK0/gravizo/master/README.md)
<details> 
<summary></summary>
custom_mark10
  digraph G {
    size ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf};
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
custom_mark10
</details>

Hmm. Okay, that's interesting... perhaps a slightly more difficult method than I hoped. This is pointing somewhere else, so we have to make it point to the right place? Or is there a way to inline it into the URL?

**Comment by samhatchett** [comment]
yeah, I've used Gravizo in the past, but it looks like GitHub changed some things which had the result of making this a whole lot more cumbersome...

Here's an alternative - what do you think?

https://yuml.me/edit/acd80eeb
![2d05ac07](https://user-images.githubusercontent.com/2386549/41246359-d7ce1eac-6d78-11e8-985e-a35a12d3a599.png)

**Comment by samhatchett** [comment]
I've roughed-out a different strategy for UML diagrams - seems to work way better. See the updated README for more info.
